export const animals: Record<string, string[][]> = {
  bear: [["bhalu"]],
  buffalo: [["bhains"]],
  camel: [["oonth"]],
  cat: [["billi"], ["kajal"]],
  chameleon: [["girgit"]],
  cow: [["gaai"]],
  crab: [["kenkada"]],
  crocodile: [["magarmachh"]],
  deer: [["hiran"]],
  dog: [["kutta"]],
  donkey: [["gadha"]],
  duck: [["battak"]],
  eagle: [["baaz"]],
  elephant: [["hathi"]],
  fox: [["lomdi"]],
  frog: [["mendak"]],
  goat: [["bakra"]],
  gorilla: [["van maanush"]],
  hippopotamus: [["jalhasti", "dariyaai ghoda"]],
  horse: [["ghoda"]],
  hyena: [["lakadbaggha"]],
  jackal: [["siyaar", "geedad"]],
  leopard: [["tendua"]],
  lion: [["sher"]],
  mole: [["chachundar"]],
  mongoose: [["nevala"]],
  monkey: [["bandar"]],
  mouse: [["chuha"]],
  owl: [["ullu"]],
  ox: [["baill"]],
  pig: [["suar"]],
  rabbit: [["khargosh"]],
  rhinoceros: [["genda"]],
  sheep: [["bhed"]],
  snake: [["saap"]],
  squirrel: [["gilahri"]],
  stag: [["baarahsingha"]],
  swan: [["hans"]],
  tiger: [["bagh"]],
  tortoise: [["kachua"]],
  wolf: [["bhediya"]],
};
